### ISSUE TITLE
Master Implementation Checklist

### ISSUE THREAD

**Issue by truephredd** [plagmada/plagmada-archives#10]
# CURRENT MILESTONE
## Develop Minimum Viable Product
- [ ] 1. Install software in staging environment
- [ ] 2. Configure users, settings, metadata fields, and collections/sets/tags
- [ ] 3. Style header/footer/landing pages
- [ ] 4. Extract data from Gallery's (current site's) gnarly SQL database (#6) (#23) (#24)
- [ ] 5. Batch-upload or otherwise transfer files
  - [ ]     \* normalize metadata
  - [ ]     \* transfer images & metadata
  - [ ]     \* spot-check transfers
- [ ] 6. Iterate on collections/sets/tags
- [ ] 7. Style individual image & metadata display pages
- [ ] 8. Style collection display pages
- [ ] 9. Test on users & iterate
- [ ] 10. Customize workflow for ongoing uploads/additions
- [ ] 11. Write introduction to gallery
- [ ] 12. Write inclusion/exclusion criteria & contribution HOWTOs (for admins and users)
- [ ] 13. Test on multiple browsers/OSes/mobile
- [ ] 14. Move from staging to replace current http://plagmada.org gallery

> For each step, please create a new issue 
> and backlink it here.

**Comment by truephredd** [comment]
OK, we are moving into the implementation phase!  @riverfr0zen & I had a call this evening and we are planning on setting up both Omeka & CA on AWS.  We can evaluate both with real data once we have some.

I've been assigned to develop a tool to acquire the data from the gallery2 site in a useful format, so that's what I'll be putting my focus on.  @riverfr0zen will be starting to set up CA and also implement Omeka plugins starting some time next week.

@brainwane @timhutchings @kwhite2
