### ISSUE TITLE
Master Launch Checklist

### ISSUE THREAD

**Issue by truephredd** [plagmada/plagmada-archives#11]
## Dependent on Implementation
- [ ] 1. Coordinate announcement with Strong Museum of Play http://www.museumofplay.org/
- [ ] 2. Media submissions 
  - BoingBoing
  - gaming sites
  - MetaFilter Projects
  - BoardGameGeek 
- [ ] 3. Outreach to local games stores, e.g., Games of Berkeley, [FLGS](https://boardgamegeek.com/wiki/page/Friendly_Local_Game_Stores_%28FLGS%29_of_the_USA)
- [ ] 4. Outreach to Wizards of the Coast & similar vendors to ask for signal-boost
- [ ] 5. Outreach to GenCon, DragonCon, other cons to ask for nonprofit booth space at upcoming events

**Comment by timhutchings** [comment]
I can start doing this stuff when we have a release date for the new archive.  

GenCon gave us a booth one year, so we know item 5 is possible.
