### ISSUE TITLE
Master Evaluation Checklist

### ISSUE THREAD

**Issue by truephredd** [plagmada/plagmada-archives#9]
## Contenders
- [x] **Omeka** http://www.omeka.org (Issue #14, #1 ) - Clears Most Hurdles
- [x] **Collective Access** http://www.collectiveaccess.org/ (Issue #21)

TWO ENTER.
ONE LEAVES
## Unsuitable
- [x] ~~MediaGoblin http://mediagoblin.org/~~ (Issue #17)
- [x] ~~Scalar http://scalar.usc.edu/scalar/~~ (Issue #19)
- [x] ~~ArchivesSpace http://www.archivesspace.org/~~  (Issue #12)
- [x] ~~Nanogallery http://nanogallery.brisbois.fr~~ (Issue #13)
- [x] ~~Zen Photo http://zenphoto.org~~ (Issue #15)
- [x] ~~Piwigo http://piwigo.org/~~ (Issue #16)
- [x] ~~Coppermine Gallery http://coppermine-gallery.net/~~ (Issue #18)
- [x] ~~Greenstone http://www.greenstone.org/~~ (Issue #20)
- [x] ~~CollectionSpace http://www.collectionspace.org/~~
- [x] ~~Almagest https://www.princeton.edu/~almagest/opensource/~~
- [x] ~~ResourceSpace http://www.resourcespace.com/~~
- [x] ~~DSpace http://www.dspace.org/introducing~~
- [x] ~~Fedora Commons http://www.fedora-commons.org/features~~
- [x] ~~EPrints http://www.eprints.org/uk/~~
- [x] ~~Invenio https://invenio.readthedocs.io/en/latest/index.html~~
- [x] ~~Islandora http://islandora.ca/~~
- [x] ~~PastPerfect http://www.museumsoftware.com/~~

> For each assessment, please create a new issue 
> and backlink it here to the appropriate package.

Let's get this list finished up by the end of the month.  
Assessments based on our **basic requirements list** from our [project plan](https://plagmada.slack.com/files/sumanah/F1N0HRBNY/plagmada-project-plan_txt.txt).

**Comment by truephredd** [comment]
OK, the first pass is complete.  We're left with four contenders.

**Comment by truephredd** [comment]
Second pass Complete.  Two left.  We're going to install both and try them out with actual data, once we capture the images and data from the extant site.
